- name: create new database for wordpress
  mysql_db:
    name: "{{ wordpress_database_name }}"
    state: present
    login_password: "{{ mysql_root_password }}"
    login_user: root

- name: create new user for wordpress
  mysql_user:
    name: "{{ wordpress_mysql_username }}"
    password: "{{ wordpress_mysql_user_password }}"
    priv: '{{ wordpress_database_name }}.*:ALL'
    state: present
    login_password: "{{ mysql_root_password }}"
    login_user: root
  
  notify:
    - restart mysql