- name: This sets up an httpd webserver
  hosts: localhost
  become: yes
  become_user: awx
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: present
    become_user: root
    become: yes
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started
