# tasks file for linux-apache2-mod_php

- name: installing apache2 and mod_php
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - apache2
    - php5-mysql
    - php5
    - php5-mcrypt
    - php5-gd
    - libapache2-mod-php5
    - libapache2-mod-auth-mysql

- name: disable the default.conf 
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: adding site and apache2 cofiguration for website
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "wordpress-website.conf.j2", dest: "/etc/apache2/sites-available/wordpress-website.conf" }
    - { src: "apache2.conf.j2", dest: "/etc/apache2/apache2.conf" }

- name: enabling the configuration
  file:
    src: "/etc/apache2/sites-available/wordpress-website.conf"
    dest: "/etc/apache2/sites-enabled/wordpress-website.conf"
    state: link

- name: adding directory permissions and ownership
  file:
    path: "{{ website_root_directory }}"
    owner: www-data
    group: www-data
    recurse: yes
    
- name: enable apache2 for starting on boot
  service:
    name: apache2
    enabled: yes
    state: started